### ISSUE TITLE
Integrate to other full note - scan - pdf softwares

### ISSUE THREAD

**Issue by VFabrice** [mzucker/noteshrink#11]
Hi, are you aware of gscan2pdf (http://gscan2pdf.sourceforge.net/) or paperwork (https://github.com/twostairs/paperwork). Could be wonderful to integrate your work to a full note-scan-pdf software. Regards

**Comment by mzucker** [comment]
Was not aware of those projects, thanks for the tip. I think since my code is a small standalone script with relatively few dependencies, it might be possible for the authors of these projects to include an option to invoke it (or embed the code itself, if they like). Since my code is MIT licensed, I expect there wouldn't be any licensing headaches if anyone decided to adopt it into their project.

Probably you would be better off filing an issue against the projects themselves if you are interested in seeing this happen.
